branch-defaults:
  default:
    environment: Tng27-env
environment-defaults:
  Tng27-env:
    branch: null
    repository: null
global:
  application_name: tng27
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/Node.js running
    on 64bit Amazon Linux/4.2.1
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: tgfjt
  sc: null
  workspace_type: Application
