version: 2
jobs:
  build:
    docker:
      - image: gradientco/node-elastic-beanstalk:7.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-modules
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - deploy:
          name: EB Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              eb deploy Tng27-env
            fi